apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: credit-risk-ai
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bittush8789/credit-risk-ai-underwriting.git
    targetRevision: main
    path: kserve
  destination:
    server: https://kubernetes.default.svc
    namespace: credit-risk-model
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
