apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: credit-risk-predictor
  namespace: credit-risk-model
spec:
  predictor:
    serviceAccountName: sa-s3-access
    sklearn:
      storageUri: s3://credit-risk-bucket/v4/model.pkl
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: "500m"
          memory: 1Gi
